language: java
jdk:
  - openjdk8
sudo: required
os:
  - linux
dist: xenial
install:
  - sudo add-apt-repository -y ppa:jonathonf/python-2.7
  - sudo apt-get update
  - sudo apt-get install --only-upgrade python
  - wget https://bootstrap.pypa.io/get-pip.py
  - sudo python get-pip.py
  - sudo pip install mkdocs
  - sudo pip install mkdocs-material
script: 
    - ./gradlew buildJar buildWar buildCli buildDoc -PbuildNumber=${TRAVIS_JOB_NUMBER} #&& ./e2e/integration_tests.sh
#    - ./gradlew jacocoTestReport
    - cp ./dist/catgenome.jar ./docker/core
    - cp ./dist/ngb-cli.tar.gz ./docker/core
    - gcloud config set project prj-ngb
    - gcloud app deploy ./docker/core/app.yaml
after_success:
  - bash <(curl -s https://codecov.io/bash)

before_install:
  - openssl aes-256-cbc -K $encrypted_7a234daff3f0_key -iv $encrypted_7a234daff3f0_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
  - if [ ! -d ${HOME}/google-cloud-sdk ]; then
    curl https://sdk.cloud.google.com | bash;
    fi
  - tar -xzf credentials.tar.gz
  - gcloud auth activate-service-account --key-file client-secret.json
#  - ssh-keygen -q -N "" -f ~/.ssh/google_compute_engine
