language: java
jdk:
  - openjdk8
sudo: required
os:
  - linux
dist: xenial
install:
  - sudo add-apt-repository -y ppa:jonathonf/python-2.7
  - sudo apt-get update
  - sudo apt-get install --only-upgrade python
  - wget https://bootstrap.pypa.io/get-pip.py
  - sudo python get-pip.py
  - sudo pip install mkdocs
  - sudo pip install mkdocs-material
script: 
    - ./gradlew buildJar buildWar buildCli buildDoc -PbuildNumber=${TRAVIS_JOB_NUMBER} && ./e2e/integration_tests.sh
    - ./gradlew jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - cp ./dist/catgenome.jar ./docker/core
  - cp ./dist/ngb-cli.tar.gz ./docker/core
before_install:
  - openssl aes-256-cbc -K $encrypted_7a234daff3f0_key -iv $encrypted_7a234daff3f0_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
  - tar -xzf credentials.tar.gz
#- ssh-keygen -q -N "" -f ~/.ssh/google_compute_engine
deploy:
  provider: gae
  keyfile: client-secret.json
  project: prj-ngb
  config: docker/core/app.yaml
  on:
    branch: feature/appengine_v1

#deploy:
#  - provider: script
#    skip_cleanup: true
#    script: DEMO_PATH=${DEMO_PATH}/dev && ./publish.sh
#    on:
#      branch: develop
#  - provider: script
#    skip_cleanup: true
#    script: ./publish.sh
#    on:
#      branch: master
